cmake: Add missing XCB::DAMAGE dependency
If libxcb-damage0-dev is not installed and kwin is compiled with
KWIN_BUILD_X11=ON then compile fails with

    kwin/src/main.cpp:71:10: fatal error: xcb/damage.h: No such
    file or directory

Add the missing DAMAGE dependency to cmake what now lets compile
fail on cmake-stage with a proper error-message that the CXB
DAMAGE dependency is missing.