core: use std::numeric_limits
This fixes a missing <climits> for INT_MIN/INT_MAX:

```
.../kwin-6.6.49.9999/src/core/region.h: In static member function ‘static KWin::Region KWin::Region::infinite()’:
.../kwin-6.6.49.9999/src/core/region.h:520:19: error: ‘INT_MIN’ was not declared in this scope
  520 |     return Region(INT_MIN / 2, INT_MIN / 2, INT_MAX, INT_MAX);
      |                   ^~~~~~~
```

(cherry picked from commit 9a0f09d54c33cd688eaaea2f91a1ffc593ae43aa)