Replace uint with unsigned int
Improves portability by avoiding the non-standard 'uint'. For example
this fixes building with musl libc:

".../kwin_wrapper.c:45:9: error: unknown type name 'uint';
    did you mean 'int'?"

(cherry picked from commit 7db93b7cd7ab860eb05e5267797e24430caa918a)