Fix build on 32bit platforms
error: invalid cast from type ‘uintptr_t’ {aka ‘unsigned int’} to type ‘EGLNativeWindowType’ {aka ‘long unsigned int’}


(cherry picked from commit e26ea6bf2313c021db7e5ca5454cd8b1e2e2037f)