Cleanup HAVE_LIBDRM_FAUX ifdefs
error: ‘HAVE_LIBDRM_FAUX’ is not defined, evaluates to ‘0’ [-Werror=undef]

This is a followup of commit cafbabd614398ca54ea9169f2667343327212927
CCMAIL: xaver.hugl@kde.org